"""Initial schema

Revision ID: 75fc772b4628
Revises: 
Create Date: 2026-09-06 22:10:50.939172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fc772b4628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ed_stays',
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=True),
    sa.Column('intime', sa.DateTime(), nullable=True),
    sa.Column('outtime', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('arrival_transport', sa.String(length=50), nullable=True),
    sa.Column('disposition', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_index(op.f('ix_ed_stays_stay_id'), 'ed_stays', ['stay_id'], unique=False)
    op.create_index(op.f('ix_ed_stays_subject_id'), 'ed_stays', ['subject_id'], unique=False)
    op.create_table('triage_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('llm_raw_response', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('possible_conditions', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severitylevel'), nullable=True),
    sa.Column('evidence_stay_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('icd_code', sa.String(length=20), nullable=True),
    sa.Column('icd_version', sa.Integer(), nullable=True),
    sa.Column('icd_title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['ed_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_stay_id'), 'diagnoses', ['stay_id'], unique=False)
    op.create_table('med_reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gsn', sa.String(length=20), nullable=True),
    sa.Column('ndc', sa.String(length=20), nullable=True),
    sa.Column('etc_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['ed_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_med_reconciliations_stay_id'), 'med_reconciliations', ['stay_id'], unique=False)
    op.create_table('pyxis_medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gsn_rn', sa.Integer(), nullable=True),
    sa.Column('charttime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['ed_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyxis_medications_stay_id'), 'pyxis_medications', ['stay_id'], unique=False)
    op.create_table('triage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('acuity', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severitylevel'), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('resp_rate', sa.Float(), nullable=True),
    sa.Column('o2sat', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('pain', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['ed_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_chief_complaint'), 'triage', ['chief_complaint'], unique=False)
    op.create_index('ix_triage_chief_complaint_gin', 'triage', ['chief_complaint'], unique=False)
    op.create_index(op.f('ix_triage_severity'), 'triage', ['severity'], unique=False)
    op.create_index(op.f('ix_triage_stay_id'), 'triage', ['stay_id'], unique=True)
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('charttime', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('resp_rate', sa.Float(), nullable=True),
    sa.Column('o2sat', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('pain', sa.String(length=10), nullable=True),
    sa.Column('rhythm', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['ed_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_stay_id'), 'vital_signs', ['stay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_signs_stay_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_triage_stay_id'), table_name='triage')
    op.drop_index(op.f('ix_triage_severity'), table_name='triage')
    op.drop_index('ix_triage_chief_complaint_gin', table_name='triage')
    op.drop_index(op.f('ix_triage_chief_complaint'), table_name='triage')
    op.drop_table('triage')
    op.drop_index(op.f('ix_pyxis_medications_stay_id'), table_name='pyxis_medications')
    op.drop_table('pyxis_medications')
    op.drop_index(op.f('ix_med_reconciliations_stay_id'), table_name='med_reconciliations')
    op.drop_table('med_reconciliations')
    op.drop_index(op.f('ix_diagnoses_stay_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_table('triage_sessions')
    op.drop_index(op.f('ix_ed_stays_subject_id'), table_name='ed_stays')
    op.drop_index(op.f('ix_ed_stays_stay_id'), table_name='ed_stays')
    op.drop_table('ed_stays')
    # ### end Alembic commands ###
